### ISSUE TITLE
[Meson] CI for meson project

### ISSUE THREAD

**Issue by ninjaoflight** [SRombauts/SQLiteCpp#403]
## Description

Happy new Year!

As Meson support is becoming more stable it would be good to have a CI for the meson project so we can check any bug or edge case like #394 or #378 this issue should be a good starting point in order to define how the CI should look like along with any feedback that is required in order to complete it, additionally having this CI will help us add any new feature that may not be included con CMake or Meson itself so it can be fixed and tested carefully before merging

an initial proposed format should look like the example of the first comment
as you may notice it is pretty similar to the CI that is already in CMake, but needs to be checked/reviewed first in order to check if everything is working good before opening a PR.

please let me know what do you think or if you have any idea/sugestion.

**Comment by ninjaoflight** [comment]
```yaml
name: build

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest MSVC",
            os: windows-latest,
            generator: "Visual Studio 17 2022",
            build_type: "Debug",
            cc: "cl", cxx: "cl",
            extra_path: "",
          }
        - {
            name: "Windows Latest MinGW",
            os: windows-latest,
            generator: "MinGW Makefiles",
            build_type: "Debug",
            cc: "gcc", cxx: "g++",
            extra_path: "C:\\ProgramData\\chocolatey\\lib\\mingw\\tools\\install\\mingw64\\bin",
          }
        - {
            name: "Ubuntu Latest GCC",
            os: ubuntu-latest,
            generator: "Unix Makefiles",
            build_type: "Debug",
            cc: "gcc", cxx: "g++",
            extra_path: ""
          }
        - {
            name: "macOS Latest Clang",
            os: macos-latest,
            generator: "Unix Makefiles",
            build_type: "Debug",
            cc: "clang", cxx: "clang++",
            extra_path: ""
          }

    steps:
    - uses: actions/checkout@v2
    - name: submodule
      run: git submodule update --init --recursive
    - name: extra_path
      shell: bash
      run: echo "${{matrix.config.extra_path}}" >> $GITHUB_PATH
    - name: configure
      shell: cmake -P {0}
      run: |
        set(ENV{CC} ${{matrix.config.cc}})
        set(ENV{CXX} ${{matrix.config.cxx}})
    - name: install prerequisites
      run: |
        # asuming that python and pip are already installed
        pip3 install meson
    - name: setup meson project
      run: |
        # setup the build directory with tests and examples enabled
        meson setup builddir -DSQLITECPP_BUILD_TESTS=true -DSQLITECPP_BUILD_EXAMPLES=true
    - name: build meson project
      run: |
        # build the project
        meson compile -C builddir
    - name: test
      run: |
        # run the tests
        meson test -C builddir
```
